### ISSUE TITLE
valores hardcoded

### ISSUE THREAD

**Issue by raulikeda** [gabriellm1/ProjetoCloud#1]
An error occurred (AuthFailure) when calling the DeregisterImage operation: Not authorized for image:ami-4050963d
An error occurred (InvalidGroup.NotFound) when calling the DescribeSecurityGroups operation: The security group 'WS' does not exist in default VPC 'vpc-716fa90b'

Isso acontece quando roda em outra conta. Os valores estão hardcoded para funcionar apenas na conta de desenvolvimento.

**Comment by raulikeda** [comment]
Na verdade o erro é outro:

Security Group do webserver criado

Traceback (most recent call last):
  File "script_B.py", line 347, in <module>
    TagSpecifications=[{'ResourceType': 'instance','Tags': [{'Key': 'WebServerInter','Value': 'Gabriel'}]}]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/client.py", line 272, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/client.py", line 576, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidGroup.NotFound) when calling the RunInstances operation: The security group 'sg-06b18f26b24990b54' does not exist in VPC 'vpc-716fa90b'

Ele está tentando usar um SG que não existe.

**Comment by raulikeda** [comment]
Analisando o código parece ser um problema de esperar o SG ser criado.
